language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-phaserify' ]; then cd .. && eval "mv $currentfolder generator-phaserify" && cd generator-phaserify; fi

